server:
  port: 8765
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie
        - id: message
          uri: lb://message-sender-service
          predicates:
            - Path=/api/messages/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie            
        - id: chat
          uri: lb://chat-service
          predicates:
            - Path=/api/chats/**
        - id: avatar
          uri: lb://avatar-service
          predicates:
            - Path=/api/avatars/**
          filters:
            - TokenRelay=
            - RemoveRequestHeader=Cookie            
        - id: jwt
          uri: lb://jwt-server-service
          predicates:
            - Path=/api/jwt/** 
  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: gateway
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri: "http://127.0.0.1:8765/login/oauth2/code/{registrationId}"
            scope: openid,resource.read
        provider:
          spring:
            issuer-uri: ${AUTHORIZATION_SERVICE:http://localhost:9002}
            authorization-uri: ${AUTHORIZATION_SERVICE:http://localhost:9002}/oauth2/authorize
            token-uri: ${AUTHORIZATION_SERVICE:http://localhost:9002}/oauth2/token

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.security.oauth2: INFO
    #    org.springframework.boot.autoconfigure: DEBUG
#    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE      
    
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
